#!/bin/bash

###########################################################################
#   Copyright (C) 2020 by Mike Hewson  [ any & all errors are mine :-) ]  #
#   hewsmike[AT]iinet.net.au                                              #
#                                                                         #
#   This file is part of Einstein@Home.                                   #
#                                                                         #
#   Einstein@Home is free software: you can redistribute it and/or modify #
#   it under the terms of the GNU General Public License as published     #
#   by the Free Software Foundation, version 2 of the License.            #
#                                                                         #
#   Einstein@Home is distributed in the hope that it will be useful,      #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with Einstein@Home. If not, see <http://www.gnu.org/licenses/>. #
#                                                                         #
###########################################################################

ROOT=`pwd`

echo "*****************************************************************"
echo "**** Building linux and win32 targets for product starsphere ****"
echo "*****************************************************************"

# First try to build for linux. 
./topbuild.sh --linux --debug -- starsphere
if [ $? -ne 0 ] then
    echo "An error occurred while making the linux product".
    exit 1 
fi

# Only proceed with win32 build if the linux build was OK.
./topbuild.sh --win32 --debug --starsphere
if [ $? -ne 0 ] then
    echo "An error occurred while making the win32 product".
    exit 2 
fi

# Both builds good, so get their products to local directory.
mkdir dist
cd dist
cp -f $ROOT/linux/dist/graphics* graphics_TEST$1_linux64
cp -f $ROOT/win32/dist/graphics* graphics_TEST$1_win32

echo "*****************************************************************"
echo "**** Successful build of both products **************************"
echo "*****************************************************************"

exit 0
